name: aurat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  calendar_date_picker2: ^0.5.2
  table_calendar: ^3.0.9
  path_provider: ^2.0.14
  fluttertoast: ^8.2.1
  sqflite: ^2.2.8
  carousel_slider: ^4.2.1
  dropdown_button2: ^2.1.0
  shared_preferences: ^2.1.0
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/image/

